### ISSUE TITLE
Cannot flash diy esp32-POE - EFR32MG21 board

### ISSUE THREAD

**Issue by willumpie82** [mercenaruss/zigstar_addons#36]
Hi, I have a custom build zigbe POE adapter (EZSP v8; 6.9.0.0 build 178) so to continue with z2m, I need to upgrade it to 7.4

- Controller is an ESP32 POE board from ttgo with ESPhome (based on TubeZB config)
- Zigbee SM-011 [EFR32MG21] (snatched from a zb-gw04-1v1), but cannot recall what exact fw package i flashed :-( 

`zeroconf:`
`  - service: tubeszb`
`    protocol: tcp`
`    port: 6638`
`    txt:`
`      version: 1.0`
`      name: TubesZB`
`      radio_type: ezsp`
`      baud_rate: 115200`
`      data_flow_control: software`

with z2m 1.36 it works fine, but need to upgrade for the next release (ezsp = obsolete)

I tried both 
- firmware_builds/zb-gw04-1v1/ncp-uart-hw-v7.4.2.0-zb-gw04-1v1-115200.gbl
- firmware_builds/zb-gw04-1v1/ncp-uart-hw-v7.4.2.0-zb-gw04-1v1-230400.gbl

but I think there is a communication issue with the zigbee controller, can someone help me decode the output below
with 'debug' enabled I get this output:

2024-05-06 18:13:25 193f5383-zigstar-silabs-flasher bellows.ezsp.protocol[154] DEBUG Send command getMfgToken: (<EzspMfgTokenId.MFG_STRING: 1>,)
2024-05-06 18:13:25 193f5383-zigstar-silabs-flasher bellows.uart[154] DEBUG Sending: b'224321a95f2a1429a87e'
2024-05-06 18:13:25 193f5383-zigstar-silabs-flasher bellows.uart[154] DEBUG Data frame: b'2343a1a95f2a054da66bb5da55aa6db663b1d854123198af247e'
2024-05-06 18:13:25 193f5383-zigstar-silabs-flasher bellows.uart[154] DEBUG Sending: b'83401b7e'
2024-05-06 18:13:25 193f5383-zigstar-silabs-flasher bellows.ezsp.protocol[154] DEBUG Application frame received getMfgToken: [b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff']
2024-05-06 18:13:25 193f5383-zigstar-silabs-flasher bellows.ezsp[154] DEBUG Read MFG_STRING token: b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff'
2024-05-06 18:13:25 193f5383-zigstar-silabs-flasher bellows.ezsp.protocol[154] DEBUG Send command getMfgToken: (<EzspMfgTokenId.MFG_BOARD_NAME: 2>,)
2024-05-06 18:13:25 193f5383-zigstar-silabs-flasher bellows.uart[154] DEBUG Sending: b'334021a95f2a1758317e'
2024-05-06 18:13:25 193f5383-zigstar-silabs-flasher bellows.uart[154] DEBUG Data frame: b'3440a1a95f2a054da66bb5da55aa6db663b1d854123198022a7e'
2024-05-06 18:13:25 193f5383-zigstar-silabs-flasher bellows.uart[154] DEBUG Sending: b'8430fc7e'
2024-05-06 18:13:25 193f5383-zigstar-silabs-flasher bellows.ezsp.protocol[154] DEBUG Application frame received getMfgToken: [b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff']
2024-05-06 18:13:25 193f5383-zigstar-silabs-flasher bellows.ezsp[154] DEBUG Read MFG_BOARD_NAME token: b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff'
2024-05-06 18:13:25 193f5383-zigstar-silabs-flasher bellows.ezsp.protocol[154] DEBUG Send command getValue: (<EzspValueId.VALUE_VERSION_INFO: 17>,)
2024-05-06 18:13:25 193f5383-zigstar-silabs-flasher bellows.uart[154] DEBUG Sending: b'444121a9fe2a04284a7e'
2024-05-06 18:13:25 193f5383-zigstar-silabs-flasher bellows.uart[154] DEBUG Data frame: b'4541a1a9fe2a15b5eb944c2caa55385ec87e'
2024-05-06 18:13:25 193f5383-zigstar-silabs-flasher bellows.uart[154] DEBUG Sending: b'8520dd7e'
2024-05-06 18:13:25 193f5383-zigstar-silabs-flasher bellows.ezsp.protocol[154] DEBUG Application frame received getValue: [<EzspStatus.SUCCESS: 0>, b'\xb2\x00\x06\t\x00\x00\xaa']
2024-05-06 18:13:25 193f5383-zigstar-silabs-flasher bellows.uart[154] DEBUG Connection lost: None
2024-05-06 18:13:25 193f5383-zigstar-silabs-flasher bellows.uart[154] DEBUG Closed serial connection
2024-05-06 18:13:25 193f5383-zigstar-silabs-flasher universal_silabs_flasher.flasher[154] INFO Detected ApplicationType.EZSP, version '6.9.0.0 build 178' (6.9.0.0.178) at 115200 baudrate (bootloader baudrate None)
2024-05-06 18:13:25 193f5383-zigstar-silabs-flasher zigpy.serial[154] DEBUG Opening a serial connection to 'socket://192.168.2.105:6638' (115200 baudrate)
2024-05-06 18:13:26 193f5383-zigstar-silabs-flasher bellows.ezsp[154] DEBUG Resetting EZSP
2024-05-06 18:13:26 193f5383-zigstar-silabs-flasher bellows.uart[154] DEBUG Resetting ASH
2024-05-06 18:13:26 193f5383-zigstar-silabs-flasher bellows.uart[154] DEBUG Sending: b'1ac038bc7e'
2024-05-06 18:13:28 193f5383-zigstar-silabs-flasher bellows.uart[154] DEBUG RSTACK Version: 2 Reason: RESET_SOFTWARE frame: b'c1020b0a527e'
2024-05-06 18:13:28 193f5383-zigstar-silabs-flasher bellows.ezsp.protocol[154] DEBUG Send command version: (4,)
2024-05-06 18:13:28 193f5383-zigstar-silabs-flasher bellows.uart[154] DEBUG Sending: b'004221a850ed2c7e'
2024-05-06 18:13:28 193f5383-zigstar-silabs-flasher bellows.uart[154] DEBUG Data frame: b'0142a1a85c2815dbd4dd7e'
2024-05-06 18:13:28 193f5383-zigstar-silabs-flasher bellows.uart[154] DEBUG Sending: b'8160597e'
2024-05-06 18:13:28 193f5383-zigstar-silabs-flasher bellows.ezsp.protocol[154] DEBUG Application frame received version: [8, 2, 26880]
2024-05-06 18:13:28 193f5383-zigstar-silabs-flasher bellows.ezsp[154] DEBUG Switching to EZSP protocol version 8
2024-05-06 18:13:28 193f5383-zigstar-silabs-flasher bellows.ezsp.protocol[154] DEBUG Send command version: (8,)
2024-05-06 18:13:28 193f5383-zigstar-silabs-flasher bellows.uart[154] DEBUG Sending: b'7d314221a9542a1d8cdf7e'
2024-05-06 18:13:28 193f5383-zigstar-silabs-flasher bellows.uart[154] DEBUG Data frame: b'1242a1a9542a1db059fd73067e'
2024-05-06 18:13:28 193f5383-zigstar-silabs-flasher bellows.uart[154] DEBUG Sending: b'82503a7e'
2024-05-06 18:13:28 193f5383-zigstar-silabs-flasher bellows.ezsp.protocol[154] DEBUG Application frame received version: [8, 2, 26880]
2024-05-06 18:13:28 193f5383-zigstar-silabs-flasher bellows.ezsp[154] DEBUG EZSP Stack Type: 2, Stack Version: 6900, Protocol version: 8
2024-05-06 18:13:28 193f5383-zigstar-silabs-flasher bellows.ezsp.protocol[154] DEBUG Send command launchStandaloneBootloader: (1,)
2024-05-06 18:13:28 193f5383-zigstar-silabs-flasher bellows.uart[154] DEBUG Sending: b'224321a9db2a14ce327e'
2024-05-06 18:13:28 193f5383-zigstar-silabs-flasher bellows.uart[154] DEBUG Data frame: b'2343a1a9db2a1544a27e'
2024-05-06 18:13:28 193f5383-zigstar-silabs-flasher bellows.uart[154] DEBUG Sending: b'83401b7e'
2024-05-06 18:13:28 193f5383-zigstar-silabs-flasher bellows.ezsp.protocol[154] DEBUG Application frame received launchStandaloneBootloader: [<EmberStatus.SUCCESS: 0>]
2024-05-06 18:13:28 193f5383-zigstar-silabs-flasher bellows.uart[154] DEBUG Connection lost: None
2024-05-06 18:13:28 193f5383-zigstar-silabs-flasher bellows.uart[154] DEBUG Closed serial connection
2024-05-06 18:13:28 193f5383-zigstar-silabs-flasher universal_silabs_flasher.flasher[154] INFO Probing ApplicationType.GECKO_BOOTLOADER at 115200 baud
2024-05-06 18:13:28 193f5383-zigstar-silabs-flasher zigpy.serial[154] DEBUG Opening a serial connection to 'socket://192.168.2.105:6638' (115200 baudrate)
2024-05-06 18:13:28 193f5383-zigstar-silabs-flasher universal_silabs_flasher.common[154] DEBUG Connection made: <_SelectorSocketTransport fd=3 read=idle write=<idle, bufsize=0>>
2024-05-06 18:13:28 193f5383-zigstar-silabs-flasher universal_silabs_flasher.common[154] DEBUG Sending data b'3'
Traceback (most recent call last):
  File "/usr/local/bin/universal-silabs-flasher", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/universal_silabs_flasher/flash.py", line 36, in inner
    return asyncio.run(f(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/universal_silabs_flasher/flash.py", line 392, in flash
    await flasher.enter_bootloader()
  File "/usr/local/lib/python3.11/site-packages/universal_silabs_flasher/flasher.py", line 305, in enter_bootloader
    await self.probe_app_type(types=[ApplicationType.GECKO_BOOTLOADER])
  File "/usr/local/lib/python3.11/site-packages/universal_silabs_flasher/flasher.py", line 261, in probe_app_type
    raise RuntimeError("Failed to probe running application type")
RuntimeError: Failed to probe running application type
[18:13:30] INFO: universal-silabs-flasher-up script exited with code 1
s6-rc: warning: unable to start service universal-silabs-flasher: command exited 1
s6-rc: info: service banner: stopping
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
s6-rc: info: service banner successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by willumpie82** [comment]
fixed it by soldering the module back to the stick and flash 7.4 via the, universal-silabs-flasher over serial, did not re-test this add-in though
