### ISSUE TITLE
Failure to update firmware home assistant yellow

### ISSUE THREAD

**Issue by srkeynton** [mercenaruss/zigstar_addons#41]
Trying to update firmware of Home Assistant Yellow firmware in order to move to ember adapter but always fails.

Log as follows:

s6-rc: info: service banner successfully started
s6-rc: info: service universal-silabs-flasher: starting
[09:04:52] INFO: Starting universal-silabs-flasher with /dev/ttyAMA1 (bootloader baudrate 115200)
2024-06-25 09:04:53 193f5383-zigstar-silabs-flasher universal_silabs_flasher.flash[158] INFO Extracted GBL metadata: NabuCasaMetadata(metadata_version=1, sdk_version='4.4.2', ezsp_version='7.4.2.0', ot_rcp_version=None, fw_type=<FirmwareImageType.NCP_UART_HW: 'ncp-uart-hw'>, baudrate=115200)
2024-06-25 09:04:53 193f5383-zigstar-silabs-flasher universal_silabs_flasher.flasher[158] INFO Probing ApplicationType.GECKO_BOOTLOADER at 115200 baud
2024-06-25 09:04:55 193f5383-zigstar-silabs-flasher universal_silabs_flasher.flasher[158] INFO Probing ApplicationType.EZSP at 115200 baud
2024-06-25 09:05:00 193f5383-zigstar-silabs-flasher universal_silabs_flasher.flasher[158] INFO Probing ApplicationType.CPC at 460800 baud
2024-06-25 09:05:04 193f5383-zigstar-silabs-flasher universal_silabs_flasher.flasher[158] INFO Probing ApplicationType.CPC at 115200 baud
2024-06-25 09:05:09 193f5383-zigstar-silabs-flasher universal_silabs_flasher.flasher[158] INFO Probing ApplicationType.CPC at 230400 baud
2024-06-25 09:05:13 193f5383-zigstar-silabs-flasher universal_silabs_flasher.flasher[158] INFO Probing ApplicationType.SPINEL at 460800 baud
Error: Failed to probe running application type
[09:05:18] INFO: universal-silabs-flasher-up script exited with code 1
s6-rc: warning: unable to start service universal-silabs-flasher: command exited 1
s6-rc: info: service banner: stopping
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
s6-rc: info: service banner successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

Config
Network device - 127.0.0.1 [needs something here or fails to save file]
Device - /dev/ttyAMA1
Flash USB - selected
Firmware URL - https://github.com/darkxst/silabs-firmware-builder/raw/17f56a03b6b4795cace66e30b6806a33d4b39741/firmware_builds/yellow/ncp-uart-hw-v7.4.2.0-yellow-115200.gbl
Baudrate - 115200

ZHA disabled

**Comment by nick2222** [comment]
Have the same issue with Home Assistant Yellow. Running Z2M and similar config

Network device - 127.0.0.1 [needs something here or fails to save file]
Device - /dev/ttyAMA1
Flash USB - NOT selected
Firmware URL: https://github.com/darkxst/silabs-firmware-builder/raw/ember-nohw/firmware_builds/yellow/ncp-uart-hw-v7.4.3.0-yellow-115200.gbl
Baudrate - 115200
Z2M disabled

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service banner: starting

-----------------------------------------------------------
 Add-on: ZigStar Silicon Labs FW Flasher
 ZigStar Silicon Labs firmware flasher add-on
-----------------------------------------------------------
 Add-on version: 0.1.1
 You are running the latest version of this add-on.
 System: Home Assistant OS 12.4  (aarch64 / yellow)
 Home Assistant Core: 2024.7.1
 Home Assistant Supervisor: 2024.06.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service banner successfully started
s6-rc: info: service universal-silabs-flasher: starting
[16:29:46] INFO: Starting universal-silabs-flasher with socket://127.0.0.1 (bootloader baudrate 115200)
2024-07-06 16:29:48 193f5383-zigstar-silabs-flasher universal_silabs_flasher.flash[154] INFO Extracted GBL metadata: NabuCasaMetadata(metadata_version=1, sdk_version='4.4.3', ezsp_version='7.4.3.0', ot_rcp_version=None, fw_type=<FirmwareImageType.NCP_UART_HW: 'ncp-uart-hw'>, baudrate=115200)
2024-07-06 16:29:48 193f5383-zigstar-silabs-flasher universal_silabs_flasher.flasher[154] INFO Probing ApplicationType.GECKO_BOOTLOADER at 115200 baud
Traceback (most recent call last):
  File "/usr/local/bin/universal-silabs-flasher", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/universal_silabs_flasher/flash.py", line 36, in inner
    return asyncio.run(f(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/universal_silabs_flasher/flash.py", line 322, in flash
    await flasher.probe_app_type(
  File "/usr/local/lib/python3.11/site-packages/universal_silabs_flasher/flasher.py", line 229, in probe_app_type
    result = await probe_funcs[probe_method](baudrate=baudrate)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/universal_silabs_flasher/flasher.py", line 135, in probe_gecko_bootloader
    async with self._connect_gecko_bootloader(baudrate) as gecko:
  File "/usr/local/lib/python3.11/contextlib.py", line 204, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/universal_silabs_flasher/common.py", line 172, in connect_protocol
    _, protocol = await zigpy.serial.create_serial_connection(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/zigpy/serial.py", line 36, in create_serial_connection
    transport, protocol = await loop.create_connection(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1085, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1069, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 973, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 628, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 668, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 6638)
[16:29:48] INFO: universal-silabs-flasher-up script exited with code 1
s6-rc: warning: unable to start service universal-silabs-flasher: command exited 1
s6-rc: info: service banner: stopping
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
s6-rc: info: service banner successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

**Comment by mercenaruss** [comment]
For Home Assistant Yellow better to use original repository: my own is experimental.

https://github.com/home-assistant/addons/tree/master/silabs_flasher
